---
title: "R Notebook"
output: html_notebook
---
Tarea 5
```{r}
library(tidyverse)

answers <- read_csv('answers.csv')
question_tags <- read_csv('question_tags.csv')
questions <- read_csv('questions.csv')
tags <- read_csv('tags.csv')

answers
questions
question_tags
tags
```
1. Left-joining questions and tag
1.1
```{r}


questions %>%
  left_join(question_tags,by=c("id"="question_id")) 

```

1.2
```{r}

questions %>%
  left_join(question_tags,by=c("id"="question_id")) %>%
  left_join(tags,by =c("tag_id"="id"), suffix("tag_"))

  
```
1.3
```{r}
questions %>%
  left_join(question_tags,by=c("id"="question_id")) %>%
  left_join(tags,by =c("tag_id"="id"), suffix("tag_")) %>%
  replace_na(list(tag_name="only-r"))
```
1.4
```{r}
questions_with_tags <- questions %>%
  left_join(question_tags,by=c("id"="question_id")) %>%
  left_join(tags,by =c("tag_id"="id"), suffix("tag_")) %>%
  replace_na(list(tag_name="only-r"))

questions_with_tags
```

2. Comparing scores across tags

2.1
```{r}
questions_with_tags %>%
  group_by(tag_name) 
```
2.2
```{r}

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score=mean(score))
```
2.3
```{r}
questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score=mean(score))%>%
  arrange(desc(mean_score))
```
3. Finding gaps between questions and answers

3.1
```{r}

questions %>%
  inner_join(answers,by=c("id"="question_id"), suffix=c("_question","_answer"))
```

3.2
```{r}
questions %>%
  inner_join(answers,by=c("id"="question_id"), suffix=c("_question","_answer")) %>%
  mutate(gap=creation_date_answer- creation_date_question)

```
4. Joining question and answer counts

4.1
```{r}

answer_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))
```
4.2
```{r}

questions %>% 
  left_join(answer_counts, by=c("id"="question_id"))
```
4.3
```{r}
questions %>% 
  left_join(answer_counts, by=c("id"="question_id")) %>%
  replace_na(list(n=0))
```

4.4
```{r}
question_answer_counts <- questions %>% 
  left_join(answer_counts, by=c("id"="question_id")) %>%
  replace_na(list(n=0))
```

5. Joining questions, answers, and tags

5.1
```{r}

question_tags %>%
  inner_join(question_answer_counts, by = c("question_id"="id")) 
```

5.2
```{r}

question_tags %>%
  inner_join(question_answer_counts, by = c("question_id"="id")) %>%
  inner_join(tags, by = c("tag_id"="id")) %>%
  arrange(desc(n))
```

